name: Metrics
on:
  schedule: [{cron: "0 */2 * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          committer_message: Updated Github Metrics. (${filename})
          filename: github-metrics-embed.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Canada/Toronto

          # Spotify
          plugin_music: yes
          plugin_music_limit: 3
          plugin_music_mode: recent
          plugin_music_time_range: short
          plugin_music_played_at: yes
          plugin_music_provider: spotify
          plugin_music_user: .user.login
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"

          # WakaTime
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
